### ISSUE TITLE
No such file or directory - Start Jupyter

### ISSUE THREAD

**Issue by ghost** [rapidsai/helm-chart#11] opened 2020-08-02 18:42 UTC
When installing the helm chart, the Jupyter Pod has the following errors: 
```
bash: /rapids/notebooks/utils/start-jupyter.sh: No such file or directory

```

**Comment by jacobtomlinson** [comment] 2020-08-03 08:48
The Docker image may have changed upstream. Will investigate there.

**Comment by jacobtomlinson** [comment] 2020-08-04 13:37
Closing as duplicate of #1

**Closed as completed by jacobtomlinson** 2020-08-04 13:37 UTC
